Dependency updates
RGB-WG/rgb-std pull request #148
Opened 2024-02-15 19:52 UTC by dr-orlovsky

2024-02-15 21:26 UTC, crisdut reviewed
Now, the following error is occurring:

```
The transfer the actual data doesn't match the provided id.\nActual id: transfer:Cs7AAr-dHR89bcS-nJ86BwiN-QXHcMKXj-yRvgKsb3-1D8LnV#baker-manual-patent.\nExpected id: transfer:ARZGSt-jNh7wRYp-zK9cyLXX-o2psW26n-GWf9qedh-j3JxY1#clever-dispute-zipper. presents inconsistency
```

Just a testing:  If we change `self.id` in the [line](https://github.com/RGB-WG/rgb-std/pull/148/files#diff-2a54dc4f21030f78ab797cc76156cb322d2d8ecede7e48122114a6ca18d1495aR257) to `self.bindle_id()`, the error is corrected.

2024-02-15 21:32 UTC, cryptoquick reviewed
Some questions

2024-02-15 21:32 UTC, cryptoquick commented on stl/RGB20@0.1.0.sta
> +Id: GVz4mvYE94aQ9q2HPtV9VuoppcDdduP54BMKffF7YoFH#prince-scarlet-ringo
Were we supposed to lose the URN prefix?

2024-02-15 21:32 UTC, cryptoquick commented on stl/RGB20@0.1.0.sty
> +@mnemonic(montana-torso-pierre)
What's the reasoning behind providing less data here?

2024-02-16 21:11 UTC, crisdut requested changes

2024-02-16 21:11 UTC, crisdut commented on src/containers/transfer.rs
> +        ));
All items must be named types.

2024-02-22 04:05 UTC, crisdut requested changes
We have good news: all tests ran successfully in my environment, so I believe that everything is now working.

However, the only bug I found occurs when we try converting a `Bindle<Transfer>` to `string` and `string` to `Bindle<Transfer>`:

```
The transfer the actual data doesn't match the provided id.
Actual id: transfer:CeJAm5-nw1WxMzV-81DtaJSa-CTgjJ1MS-g9NmSjvi-6vMkT3#bonanza-shelter-organic.
Expected id: transfer:CgtX9T-9uVVt1Rq-3dPAs62P-CegfHe1Y-Gjs8D8Uu-onnw1L#rebel-justice-lithium. presents inconsistency
```

I think we need make some changes [here](https://github.com/RGB-WG/rgb-std/blob/5817be7600c38fcfc5e4499ca165dbfe3444aea1/src/containers/bindle.rs#L257), from `writeln!(f, "Id: {:-#}", self.id)?;` to `writeln!(f, "Id: {:-#}", self.bindle_id())?;`

If this change, this [validation](https://github.com/RGB-WG/rgb-std/blob/5817be7600c38fcfc5e4499ca165dbfe3444aea1/src/containers/bindle.rs#L237C16-L237C25) works.

2024-02-22 10:23 UTC, dr-orlovsky commented
@crisdut thank you for figuring out the source of the problem! You are right: `bindle.id` is the ID for the bindle _content_, while `bindle.bindle_id()` commits to both content AND signatures...

Shit, these id's are really getting out of control...

2024-02-22 10:53 UTC, dr-orlovsky commented
No, I  am wrong: id and bindle_id should be the same thing! At least according to the code: https://github.com/RGB-WG/rgb-std/blob/5817be7600c38fcfc5e4499ca165dbfe3444aea1/src/containers/bindle.rs#L171

Any guesses why we have this bug? I can easily fix with your suggestion above, but I am afraid we are missing some deep bug here...

2024-02-22 22:43 UTC, crisdut commented
> Any guesses why we have this bug? I can easily fix with your suggestion above, but I am afraid we are missing some deep bug here...

I found the reason.


When we create the bindle<transfer>, we use the Bindle::new method:

```rust
pub struct Bindle<C: BindleContent> {
    id: C::Id,
    data: C,
    sigs: TinyVec<Cert>,
}

impl<C: BindleContent> Bindle<C> {
    pub fn new(data: C) -> Self {
        Bindle {
            id: data.bindle_id(),
            data,
            sigs: empty!(),
        }
    }
}
```

In some cases, we modify the tranfer, and this changes producing another id when we execute bindle_id and transfer_id, but Bindle::Id remain fixed.

Example:

https://github.com/RGB-WG/rgb/blob/master/src/pay.rs#L337-L353

My recommendation is remove the directly access by id, and use always bindle_id.

What's you think?

2024-02-26 20:22 UTC, dr-orlovsky commented
@crisdut I did this way in https://github.com/RGB-WG/rgb-std/pull/148/commits/0a9c92ef073ac3c3c61390cebe94aa0da341e86d and updated RGB wallet in master. Please let me know if everything works now - and I will merge this PR

2024-02-28 09:19 UTC, merged