Interface refactoring
RGB-WG/rgb-std pull request #162
Opened 2024-03-12 07:23 UTC by dr-orlovsky

2024-03-26 20:34 UTC, dr-orlovsky commented
@zoedberg can I merge this? It is required for https://github.com/RGB-WG/rgb-std/issues/151

I mean I understand that it's hard to review; I rather expect you to check the checklist and ask if you see any red flags there. If not - I will merge and we will debug over time all things which may be wrong here

2024-03-27 10:50 UTC, zoedberg requested changes
This doesn't compile in rgb-lib because it breaks compilation of rgb-schemata. I don't think we should merge this without first having a PR for rgb-schemata.

2024-03-27 16:22 UTC, dr-orlovsky commented
@zoedberg right, fully forgot about that. Here it is: https://github.com/RGB-WG/rgb-schemata/pull/36

I will also work on the RGB wallet changes

2024-03-28 16:23 UTC, zoedberg requested changes
I've updated rgb-lib to try the PRs refactoring the interfaces (https://github.com/RGB-WG/rgb-std/pull/162, https://github.com/RGB-WG/rgb-schemata/pull/36 and https://github.com/RGB-WG/rgb/pull/154) but when doing:
```rust
let iface_nia = Rgb20::from(contract_iface);
let terms = iface_nia.contract_terms();
```
I encounter the following panic:
```rust
thread 'wallet::test::send::success' panicked at /home/zoe/.cargo/registry/src/index.crates.io-6f17d22bba15001f/strict_types-2.7.0-beta.2/src/value/val.rs:399:32:
StrictVal struct doesn't have field named terms
```

I've found a fix for this, see the provided suggestions.

After fixing this I've found another issue: before I was retrieving the asset timestamp with `contract.global("created")`, but I see this PR removed the `created` global state. Why this has been removed and how can we now retrieve this information?

2024-03-28 16:23 UTC, zoedberg commented on src/stl/specs.rs
>              .expect("invalid terms");
```suggestion
        let text = RicardianContract::from_str(&value.unwrap_struct("text").unwrap_string())
            .expect("invalid text");
```

2024-03-28 16:23 UTC, zoedberg commented on src/stl/specs.rs
> +        Self { text: terms, media }
```suggestion
        Self { text, media }
```

2024-03-28 17:10 UTC, dr-orlovsky commented
Thanks for finding a fix.

Regarding the created timestamp, it is moved into the genesis itself, as was proposed in [RCP-240227A](https://github.com/RGB-WG/RFC/issues/1) and discussed in Telegram.

If you need to have an access to it, you can just read `timestamp` property on genesis: https://github.com/RGB-WG/rgb-core/blob/e04cfffe989642eb03db4d065c6f53c1d6d218ba/src/contract/operations.rs#L317

2024-03-29 09:55 UTC, zoedberg approved these changes
Ok, thanks, sorry I missed that. I've updated rgb-lib timestamp extraction code and now all tests are passing. ACK 00f19831580384c2a1060330d0e21711fbbc3a17

2024-03-29 09:57 UTC, merged