check ifaceid, bundleid in consignment
RGB-WG/rgb-std pull request #217
Opened 2024-06-15 07:46 UTC by cymqqqq

Description: for this pull request,
1.check that interface ids match implementations(check iface id matches iface id presents in iimpl)
2.check bundle ids listed in terminals are present in the consignment(get bundle ids from indexconsignment, then check if the bundle id set contains the bundle id in the terminals)
Question: about the `check attach ids from data containers are present in operations`
I don't understand it, should we check whether the attach id from the consignment is equal to the opid present in the operations?(I mean check if the attach id is equal to the opid? If not, where do the operations come from?)
Or should we check the own state from the state transition, then check the attach id in the revealed attach state is equal to the attach id in the consignment?

2024-06-16 10:49 UTC, dr-orlovsky requested changes
Some small improvements

2024-06-16 10:49 UTC, dr-orlovsky commented on src/containers/consignment.rs
>          // TODO: check bundle ids listed in terminals are present in the consignment
We can remove these two lines

2024-06-16 10:49 UTC, dr-orlovsky commented on src/containers/consignment.rs
> +        for (bundle_id, _) in self.terminals.iter() {
```suggestion
        for bundle_id in self.terminals.keys() {
```

2024-06-16 10:49 UTC, dr-orlovsky commented on src/containers/consignment.rs
> +        let bundle_ids = index.bundle_ids().collect::<BTreeSet<_>>();
We do not need this extra allocation - see below

2024-06-16 10:49 UTC, dr-orlovsky commented on src/containers/consignment.rs
> +            if !bundle_ids.contains(bundle_id) {
```suggestion
            if !index.bundle_ids().any(|id| id == bundle_id) {
```

2024-06-16 10:49 UTC, dr-orlovsky commented on src/containers/consignment.rs
> +                    "bundle ids listed in terminals doesn't present in the consignment"
```suggestion
                    "terminal bundle id {bundle_id} is not present in the consignment"
```

2024-06-16 10:50 UTC, dr-orlovsky commented
> check attach ids from data containers are present in operations

This means that all attachments which are part of the consignment must be used in some operations as a state - i.e. there must be no excessive unused attachments bloating the size of the consignment

2024-06-17 04:00 UTC, cymqqqq commented
Sorry, it's my misoperation to remove the assignee.

2024-06-17 08:49 UTC, dr-orlovsky requested changes
Two more things and we are good to go

2024-06-17 08:49 UTC, dr-orlovsky commented on src/containers/consignment.rs
> +                status.add_warning(Warning::Custom(s!(
```suggestion
                status.add_warning(Warning::Custom(format!(
```

Otherwise `bundle_id` will not get into the string

2024-06-17 08:49 UTC, dr-orlovsky commented on src/containers/consignment.rs
> +                )));
This should help with debugging:
```suggestion
                status.add_warning(Warning::Custom(format!(
                    "implementation {} targets different interface {} than expected {}", iimpl.impl_id(), iimpl.iface_id, iface.iface_id()
                )));
```

2024-06-17 13:04 UTC, dr-orlovsky approved these changes
ACK 434d0e9ccb1e002e3aa7d42ea628d6540da43b17

2024-06-17 13:05 UTC, merged